#!/bin/sh

set -e

cd "$(git rev-parse --show-toplevel)"

echo "🔍 Running pre-commit…"

echo "🧹 Cleaning project…"
cargo clean

echo "🎨 Formatting code…"
cargo fmt

echo "📦 Checking build…"
cargo check

echo "📎 Running clippy…"
cargo clippy -- -D warnings

echo "✅ Everything OK in pre-commit"