name: nyx-ci
run-name: "🛠️ CI №${{ github.run_number }}.${{ github.run_attempt }}, ${{ github.event_name }} by ${{ github.actor }}."

on:
  push:
    branches:
      - main
      - dev
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: src

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: src/go.mod
          cache: true
          cache-dependency-path: src/go.sum

      - name: Download dependencies
        run: go mod download

      - name: Check formatting
        run: |
          test -z "$(gofmt -l .)"

      - name: Run tests
        run: go test ./...

      - name: Build
        run: go build ./...
